### PR TITLE
DSND-3026: Update events processing order for upsert psc statements

### PR DESCRIPTION
**Pull request by kinpang-CH**
* Change repository query to not check for equal on delta at
* Remove transactional annotation
* Update tests
* Update pom.xml for UTC timezone change
* Passes local testing

Resolves [DSND-3026](https://companieshouse.atlassian.net/browse/DSND-3026)

[DSND-3026]: https://companieshouse.atlassian.net/browse/DSND-3026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Review by johncook-ch — APPROVED** [review]

**Review by sthompsonCH — APPROVED** [review]

**Review by crowlandsCH — APPROVED** [review]

**Pull request merged**
