### PR TITLE
DSND-3114: Add DeltaAt to DELETE endpoint header

### PR DESCRIPTION
**Pull request by mturner-CH**
* Refactor delete service to take deltaAt as parameter
* Update service to check against request and existing deltaAt
* Update service to process delete when resource does not exist
* Refactor kafka api invocation to take ResourceChangedRequest document
* Removed unused method hasPscExemptions from service

Resolves: [DSND-3114](https://companieshouse.atlassian.net/browse/DSND-3114)

[DSND-3114]: https://companieshouse.atlassian.net/browse/DSND-3114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by cgregoryCH — APPROVED** [review]
Looks great

**Review by kinpang-CH — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Pull request merged**
